### ISSUE TITLE
issue running with mounted volume

### ISSUE THREAD

**Issue by aficustree** [codekitchen/alarmdecoder-webapp-dockerfile#2]
I'm using your docker image on a Synology with the alarmdecoder connected. 

This docker run command works

```
docker run --restart "always" -p 0.0.0.0:2222:5000/tcp --device=/dev/ttyUSB0 --detach=true --name "AlarmDecoderWebUI" --net="bridge" codekitchen/alarmdecoder-webapp:latest
```

but the following run command

```
docker run --restart "always" --volume="/volume1/docker/alarmdecoder:/opt/alarmdecoder-webapp/instance:rw" -p 0.0.0.0:2222:5000/tcp --device=/dev/ttyUSB0 --detach=true --name "AlarmDecoderWebUI" --net="bridge" codekitchen/alarmdecoder-webapp:latest
```

results in a constant restart with 

```
ERROR in app [/opt/alarmdecoder-webapp/ad2web/app.py:171]:
Could not find 'settings' table in the database.  You may need to run 'python manage.py initdb'.
```

I see that the command is run in the dockerfile. Any ideas? The directory on the docker host looks good

```
drwxrwxrwx  1 root root 52 Nov  9 20:27 .
drwxr-xr-x+ 1 root root 94 Oct 11 20:35 ..
-rw-r--r--  1 1000 1000  0 Nov  9 20:27 db.sqlite
drwxr-xr-x  1 1000 1000 16 Nov  9 20:27 logs
drwxr-xr-x  1 1000 1000  0 Nov  9 20:27 openid
drwxr-xr-x  1 1000 1000  0 Nov  9 20:27 uploads
```

Do i actually need to mount `/opt/alarmdecoder-webapp/` instead of `/opt/alarmdecoder-webapp/instance/`?

**Comment by codekitchen** [comment]
`/opt/alarmdecoder-webapp/instance` is correct. I've never tried running this container with a host-mounted volume, just a native docker volume.

I believe the problem is that I'm initializing the db with `RUN python manage.py initdb` in the Dockerfile, so that if using a native docker volume, that initialized db will get copied into the new volume on initialization. When using a host-mounted volume, docker doesn't do that initial initialization/copy of the volume, though. I bet if we moved that `initdb` command to `run.sh` instead, it'd work. That's probably better practice anyway. I'll make that change and try it out.

**Comment by aficustree** [comment]
ah cool, also it looks like the alarmdecoder library actually needs to be at version 1.13.1 for the [API to work](https://github.com/nutechsoftware/alarmdecoder-webapp/issues/21)). Suggestion is to replace the alarmdecoder line in requirements with `git+https://github.com/nutechsoftware/alarmdecoder#1.13.1` until they update pip

**Comment by aficustree** [comment]
see pull request
